version: 2
jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Update libraries
          command: 'apt-get update -y'    

      - run:
          name: Compiling project
          command: ls
          
workflows:
  version: 2
  build:
    jobs:
      - build
