version: 2
jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Update libraries
          command: 'apt-get update -y'
      - run:
          name: Install Essential
          command: 'apt-get install build-essential -y'
      - run: 
          name: Install SFML
          command: 'apt-get install libsfml-dev -y'
      - run:
          name: Compiling project
          command: 'make'
          
workflows:
  version: 2
  build:
    jobs:
      - build
