version: 2
jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run: echo marc
  test:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run: echo marc
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
