version: 2
jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Update libraries
          command: 'apt-get update'    
      - run: 
          name: Install SFML
          command: 'apt-get install libsfml-dev'
      - run:
          name: Compiling project
          command: pwd
          
workflows:
  version: 2
  build:
    jobs:
      - build
