version: 2
jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run: 
          name: Install SFML
          commmand: 'sudo apt-get install libsfml-dev'
          
workflows:
  version: 2
  build:
    jobs:
      - build
      - test
